version: "3"
services:
 api_prod:
  image: 35.161.193.182:5000/homecolis-api
  deploy:
   replicas: 3
   placement:
    constraints: [node.env == production]
  environment:
   - SERVICE_PORTS="80"
   - MONGO_USER=user
   - MONGO_DATABASE=test
   - MONGO_PASSWORD=password
   - MONGO_HOST=52.34.127.90
   - NODE_ENV=production
   - VIRTUAL_HOST=api.homecolis.lb
  networks:
   - anetwork
  ports:
   - "8081:8080"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
 api_dev:
  image:  35.161.193.182:5000/homecolis-api
  deploy:
   replicas: 2
   placement:
    constraints: [node.env == development]
  environment:
   - VIRTUAL_HOST=dev.api.homecolis.lb
   - MONGO_USER=user
   - MONGO_DATABASE=test
   - MONGO_PASSWORD=password
   - MONGO_HOST=52.34.127.9O
   - NODE_ENV=production
   - SERVICE_PORTS="80"
  networks:
   - anetwork
  ports:
   - "8080:8080"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
networks:
 anetwork:
  external: true